language: ruby
rvm:
 - 2.4.1
install:
 - bundle install

services:
 - docker

before_install:
 - docker pull nginx
 - docker pull rails:onbuild

script:
 - bundle exec rake assets:precompile
 - docker build -f ./Dockerfile_backend -t mygirl_app:$TRAVIS_BUILD_NUMBER .
after_success:
 - docker images
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker tag mygirl_app:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/mygirl_app:$TRAVIS_BUILD_NUMBER && docker push $DOCKER_USERNAME/mygirl_app:$TRAVIS_BUILD_NUMBER

#deploy:
#  provider: cloudfoundry
#  username: shijingkun886@gmail.com
#  password: 
#  api: https://api.run.pivotal.io
#  organization: kun-org
#  space: development
